security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    - { name: 'admin@mail.com', password: '1', roles: 'ROLE_ADMIN' }
                    - { name: 'user@mail.com', password: '1', roles: 'ROLE_USER' }
        user_db:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: authorization
                check_path: authorization
            logout:
                path: logout
                target: /
            provider: chain_provider

    access_control:
        - { path: ^/secret, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    access_denied_url:
        /error403
